//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.29 at 07:48:20 PM EET 
//


package ViaCommanderUnMarshalling;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ViaCommanderUnMarshalling package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _UnitsCatalog_QNAME = new QName("", "units_catalog");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ViaCommanderUnMarshalling
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UnitsCatalogType }
     * 
     */
    public UnitsCatalogType createUnitsCatalogType() {
        return new UnitsCatalogType();
    }

    /**
     * Create an instance of {@link CityType }
     * 
     */
    public CityType createCityType() {
        return new CityType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnitsCatalogType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "units_catalog")
    public JAXBElement<UnitsCatalogType> createUnitsCatalog(UnitsCatalogType value) {
        return new JAXBElement<UnitsCatalogType>(_UnitsCatalog_QNAME, UnitsCatalogType.class, null, value);
    }

}
